import type { Metadata } from "next";
import "ress";
import "./globals.css";
import { Footer } from "./_components/Footer";

export const metadata: Metadata = {
  title: "みやくん",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        {children}
        <Footer />
      </body>
    </html>
  );
}
